### ISSUE TITLE
breaks while doing pre_delta_filter

### ISSUE THREAD

**Issue by yasirs** [jgurtowski/ectools#4]
When running correct.sh over some of my files, the pre_delta_filter.py breaks with the following message in the output:

```
+ FILTERED_DELTA=p0008.delta
+ [[ true == true ]]
+ FILTERED_DELTA=p0008.delta.pre
+ python /sw/ectools-master/pre_delta_filter.py p0008.delta 0.05 0.80 200 p0008.delta.pre
Traceback (most recent call last):
  File "/sw/ectools-master/pre_delta_filter.py", line 58, in <module>
    for record in getDeltaAlignmentIterator(fh):
  File "/sw/ectools-master/nucio.py", line 124, in getDeltaAlignmentIterator
    record = prepareDeltaRecord(itembuf)
  File "/swectools-master/nucio.py", line 111, in prepareDeltaRecord
    almnt.positions.append(int(buf[i]))
IndexError: list index out of range
```

I can send you the data privately if you wish.

**Comment by jgurtowski** [comment]
Yes, can you send along the delta file.
